apiVersion:34
kind:34
metadata:34
  name:34
  labels:34
    app:34
spec:34
  replicas:34
  selector:34
    matchLabels:34
      app:34
  template:34
    metadata:34
      labels:34
        app:34
    spec:34
      containers:34
      - name:34
        image:34
        ports:34
        - containerPort:34
