apiVersion:33
kind:33
metadata:33
  name:33
  labels:33
    app:33
spec:33
  replicas:33
  selector:33
    matchLabels:33
      app:33
  template:33
    metadata:33
      labels:33
        app:33
    spec:33
      containers:33
      - name:33
        image:33
        ports:33
        - containerPort:33
