apiVersion:35
kind:35
metadata:35
  name:35
  labels:35
    app:35
spec:35
  replicas:35
  selector:35
    matchLabels:35
      app:35
  template:35
    metadata:35
      labels:35
        app:35
    spec:35
      containers:35
      - name:35
        image:35
        ports:35
        - containerPort:35
